version: '3.7'

services:
    main:
        container_name: sercret-server-main
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        volumes:
            - ./src:/app/src
            - ./components:/app/components
            - ./pages:/app/pages
            - ./static:/app/static
            - ./store:/app/store
            - ./plugins:/app/plugins
        command: npm run dev
        env_file:
            - .env
        networks:
            - network
        depends_on:
            - mongo
    mongo:
        container_name: sercret-server-mongo
        image: mongo
        restart: always
        networks:
            - network
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    mongo-express:
        container_name: secret-server-mongo-express
        image: mongo-express
        restart: always
        networks:
            - network
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
        ports:
            - 8081:8081
networks:
    network: